export const Facultades = {
    "FACULTAD DE CIENCIAS NATURALES E INGENIERÍAS": [
      "TECNOLOGIA EN IMPLEMENTACION DE SISTEMAS ELECTRONICOS INDUSTRIALES",
      "INGENIERIA ELECTRONICA",
      "TECNOLOGIA EN GESTION DE SISTEMAS DE TELECOMUNICACIONES",
      "INGENIERIA DE TELECOMUNICACIONES",
      "TECNOLOGIA EN OPERACION Y MANTENIMIENTO ELECTROMECANICO",
      "INGENIERIA ELECTROMECANICA",
      "TECNOLOGIA EN MANEJO DE RECURSOS AMBIENTALES",
      "INGENIERIA AMBIENTAL",
      "TECNOLOGIA EN ELECTRICIDAD INDUSTRIAL",
      "INGENIERIA ELECTRICA",
      "TECNOLOGIA EN DESARROLLO DE SISTEMAS INFORMATICOS",
      "INGENIERIA DE SISTEMAS",
      "TECNOLOGIA EN PRODUCCION INDUSTRIAL",
      "INGENIERIA INDUSTRIAL",
      "TECNOLOGIA EN LEVANTAMIENTOS TOPOGRAFICOS",
      "TECNOLOGIA EN TOPOGRAFIA",
      "INGENIERIA EN TOPOGRAFIA",
      "TECNOLOGIA EN LOGISTICA DEL TRANSPORTE",
      "INGENIERIA EN SISTEMAS DE TRANSPORTE"
    ],
    "FACULTAD DE CIENCIAS SOCIOECONÓMICAS Y EMPRESARIALES": [
      "TECNOLOGIA EN ENTRENAMIENTO DEPORTIVO",
      "PROFESIONAL EN CULTURA FISICA Y DEPORTE",
      "TECNOLOGIA EN MANEJO DE LA INFORMACION CONTABLE",
      "CONTADURIA PUBLICA",
      "TECNOLOGIA EN GESTION DE LA MODA",
      "PROFESIONAL EN DISENO DE MODAS",
      "TECNOLOGIA EN GESTION BANCARIA Y FINANCIERA",
      "ADMINISTRACION FINANCIERA",
      "TECNOLOGIA EN MERCADEO Y GESTION COMERCIAL",
      "MERCADEO",
      "TECNOLOGIA EN GESTION EMPRESARIAL",
      "ADMINISTRACION DE EMPRESAS",
      "TECNOLOGIA EN GESTION AGROINDUSTRIAL"
    ]
  };
  